name: Auto Deploy

on:
  push:
      branches: [master]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install Yarn
          run: npm install -g yarn
        # - name: Building
        #   run: |
        #     yarn && BUILDING=true yarn run nuchain:build
        - name: Deploying
          run: |
            git config --global user.email "netizen-indo@users.noreply.github.com"
            git config --global user.name "Netizen Indonesia"
            echo "machine github.com login anvie password ${{ secrets.ACCESS_KEY }}" > ~/.netrc
            yarn && GIT_USER=anvie PUBLISHING=true yarn deploy
